name: "Build and Deploy"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libreadline-dev zlib1g-dev
          curl -sSL https://github.com/rbenv/ruby-build/archive/master.tar.gz | tar xz -C /tmp
          sudo /tmp/ruby-build-master/bin/ruby-build 3.2.2 /opt/hostedtoolcache/Ruby/3.2.2/x64
          sudo touch /opt/hostedtoolcache/Ruby/3.2.2/x64.complete

      - name: Setup Bundler
        run: gem install bundler

      - name: Build site
        run: |
          bundle install
          bundle exec jekyll build -d _site
        env:
          JEKYLL_ENV: "production"

      - name: Test site
        run: |
          bundle exec htmlproofer _site \
            --disable-external \
            --ignore-urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/"

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
